apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-appli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-appli
  template:
    metadata:
      labels:
        app: mon-appli
    spec:
      containers:
        - name: monconteneur
          image: mohamedfrikha65/mon-image:latest
          ports:
            - containerPort: 80
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: SECRET_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: STRIPE_PUBLISHABLE_KEY
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: POSTGRES_DB