# Generated by Django 5.2.11 on 2026-02-16 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=30)),
                ('date_publication', models.DateField()),
                ('resume', models.TextField()),
                ('nombre_pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='couvertures/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.catalogue')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
